#!/bin/sh

mkdir -p /etc/kubernetes/pki && \
echo $KUBEADM_B64 | base64 -d > /etc/kubernetes/kubeadm.conf && \
echo $KUBECACRT_B64 | base64 -d > /etc/kubernetes/pki/ca.crt && \
echo $KUBECAKEY_B64 | base64 -d > /etc/kubernetes/pki/ca.key && \
kubeadm kubeconfig user \
                --config /etc/kubernetes/kubeadm.conf \
                --client-name kubevip \
                --org "system:masters" > /etc/kubernetes/admin.conf